name: Run linters and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        working-directory: frontend
        uses: actions/checkout@v2

      - name: Setup and run Cupress
        working-directory: frontend
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm start

      - name: run ESLint
        working-directory: frontend
        run: npm run lint

      - name: run Prettier
        working-directory: frontend
        run: npm run format:check

      - name: Run Jest
        working-directory: frontend
        run: npm run test
